{{- if and .Values.gateway.enabled .Values.gateway.basicAuth.enabled (not .Values.gateway.basicAuth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loki.gatewayFullname" $ }}
  labels:
    {{- include "loki.gatewayLabels" $ | nindent 4 }}
  {{- with .Values.loki.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  .htpasswd: |
    {{- tpl .Values.gateway.basicAuth.htpasswd . | nindent 4 }}
{{- end }}
